name: Build and Push ARM64 Docker Image

on:
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Build ohne Cache'
        required: false
        type: boolean
        default: false

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: self-hosted
    # Falls du mehrere Runner hast, kannst du Labels verwenden:
    # runs-on: [self-hosted, macbook]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Use temporary Docker config
        run: |
          mkdir -p /tmp/docker-config
          echo '{}' > /tmp/docker-config/config.json
        env:
          DOCKER_CONFIG: /tmp/docker-config

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
        env:
          DOCKER_CONFIG: /tmp/docker-config

      - name: Build and push web app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          no-cache: ${{ github.event.inputs.no_cache == 'true' }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/domburg-booking:buildcache,ignore-error=true
          cache-to: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/domburg-booking:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/domburg-booking:latest
            ${{ env.DOCKERHUB_USERNAME }}/domburg-booking:${{ github.sha }}

